In [ ]:
%cd ~
![ ! -d "./Python_CNN" ] && echo "Github Repo DOES NOT exists."
![ ! -d "./Python_CNN" ] && git clone https://github.com/sawera261khurshid/Python_CNN.git
![ -d "./Python_CNN" ] && echo "Github Repo exist."
%cd Python_CNN
%pip install -r requirements.txt
!echo 
!echo List of files
!ls

/root
Github Repo exist.
/root/Python_CNN
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/

List of files
 cnn_keras.py			    conva1.py		   linear_biases.npy
 cnn.py				    convaa1.py		   linear_filters.npy
 CNN_Python_CIFAR.ipynb		    conv_filters_3d.npy    max1a.py
 CNN_Python.ipynb		    conv_filters.npy	   maxpool.py
 CNN_Python_MNIST_and_CIFAR.ipynb   conv_new.py		   maxpool_update.py
 cnn_scratch.py			    conv.py		   __pycache__
 CNN_Torch.ipynb		    conv_update.py	   python_cnn.py
 CNN_Torch_MNIST_and_CIFAR.py	    data.csv		   README.md
 cnn_torch.py			    data.py		   relu.py
 conv12aa1.py			    exp_both.ipynb	   requirements.txt
 conv12aa.py			    exp_both.py		   slowpool
 conv12a.py			    exp_scratch.ipynb	   soft_fc.py
 conv1a1.py			    exp_shoaib.py	   softmax.py
'conv1aa1 (1).py'		    exp_torch_both.ipynb   softmax_test.py
 conv1aa1a.py			    exp_torch.ipynb	   softmax_update.py
 conv1aa1.py			    fc22a_update.py	   solver.py

In [ ]:
# Define settings for run

debug=False

shuffle_data=False

run_train=True
run_val=True

load_saved_weights=False
weight_file='weights/best_99.pkl'

total_epoch=1
training_acc_internal=1000

In [ ]:
# Importing libraries

from logging import raiseExceptions
import os
import pickle
from tqdm import tqdm
import mnist
import numpy as np
from conv22aa2_update import Conv3x3_n_to_n_padding, Conv3x3_1_to_n_padding
from maxpool import MaxPool2
from softmax import Softmax
from relu import Relu
from softmax_test import Softmax_test
from fc22a_update import FC
from sklearn.metrics import mean_squared_error
from conv import Conv3x3

# from logging import raiseExceptions
# import os
# import pickle
# from tqdm import tqdm
# import mnist
# import numpy as np
# from conv_update import Conv3x3, Conv3x3_n_to_n_padding, Conv3x3_1_to_n_padding
# from maxpool_update import MaxPool2
# from softmax_update import Softmax
# from relu import Relu
# from softmax_test import Softmax_test
# from fc_update import FC

In [ ]:
# # Define settings for run

# debug=False

# shuffle_data=False

# run_train=True
# run_val=True

# load_saved_weights=False
# weight_file='weights/best_99.pkl'

# total_epoch=10
# training_acc_internal=1000

In [ ]:
# Initialize the network layers
conv0   = Conv3x3_1_to_n_padding(output=8)  # 28x28x1   -> 28x28x8  (Convolution with 8 filters)
pool0   = MaxPool2()                        # 28x28x8   -> 14x14x8  (MaxPooling 2x2)
conv1   = Conv3x3_n_to_n_padding(output=16, inputch=8)  # 14x14x8   -> 14x14x16 (Convolution with 8 filters)
pool1   = MaxPool2()                        # 14x14x16  -> 07x07x16 (MaxPooling 2x2)
# conv2   = Conv3x3_n_to_n_padding(output=32, input=16)
# conv3   = Conv3x3_n_to_n_padding(output=64, input=32)
fc0     = FC(7 * 7 * 16, 7 * 7 * 16)        # 784       -> 784      (FC)
fc1     = FC(7 * 7 * 16, 10)                # 784       -> 10       (FC)
softmax = Softmax()                         # 14x14x8   -> 10       (Softmax)
relu    = Relu()                            # 14x14x8   -> 10       (Softmax)

In [ ]:
conv0   = Conv3x3_1_to_n_padding(output=8)  # 28x28x1   -> 28x28x8  (Convolution with 8 filters)
weights = conv0.filters
print(weights)
print(weights.shape)

[[[ 8.76421854e-03 -2.19491217e-02 -5.17163463e-02]
  [-1.07837737e-01 -7.47438073e-02  3.05433618e-03]
  [-2.05582559e-01  2.49370024e-01 -7.28978291e-02]]

 [[-3.39461416e-02 -1.20964371e-01 -5.42755239e-02]
  [ 1.33037329e-01 -4.19276394e-02  8.68640840e-02]
  [-2.10059434e-02  9.61499885e-02 -1.16678663e-02]]

 [[-2.17765197e-02  1.94195420e-01  9.91955101e-02]
  [ 1.06845982e-01 -1.76097322e-02 -1.24855906e-01]
  [ 1.24380499e-01  1.91407382e-01 -6.45490959e-02]]

 [[-1.29245147e-01  1.04894124e-01  2.12606654e-01]
  [ 9.20044035e-02 -8.46567452e-02 -1.05196141e-01]
  [-1.79976374e-01 -1.47207707e-01  7.58061884e-03]]

 [[ 1.38613150e-01  1.16958795e-02 -1.17044784e-02]
  [ 1.06800511e-01  1.67763963e-01 -1.21352501e-01]
  [ 1.75869800e-02  1.10461324e-01 -1.73510984e-02]]

 [[-1.07559532e-01  5.56693077e-02  6.92823529e-02]
  [ 1.19759493e-01  1.91018268e-01  1.53214976e-01]
  [ 1.01159677e-01  1.12538032e-01  9.14930642e-05]]

 [[-9.99661982e-02  1.18720479e-01  1.47374094e-01]


In [ ]:
conv1  = Conv3x3_n_to_n_padding(output=16, inputch=8)  # 14x14x8   -> 14x14x16 (Convolution with 8 filters)
weights_conv1 = conv1.filters
print(weights)
print(weights.shape)

[[[ 3.13439667e-02  1.22944742e-01 -9.95859727e-02]
  [-5.07814400e-02 -8.26533064e-02  7.81429857e-02]
  [ 1.93038434e-02  2.28372633e-01  1.50134847e-01]]

 [[ 1.21661477e-01 -3.99072692e-02 -1.13154091e-01]
  [ 6.37363084e-03  1.33610979e-01  6.21094443e-02]
  [-2.60762610e-02 -1.17974915e-01 -5.20447753e-02]]

 [[-2.12246209e-01  1.94701493e-01  7.72098452e-02]
  [ 2.18349814e-01 -1.08544081e-01 -1.80429202e-02]
  [ 3.07981111e-02 -1.82971656e-01  2.16257647e-02]]

 [[ 3.18273157e-02 -2.24405229e-01  1.18732534e-01]
  [ 9.24406722e-02  7.15883151e-02  6.42885268e-03]
  [ 8.40258002e-02 -1.17074504e-01 -1.33111656e-01]]

 [[-1.21933714e-01 -1.17211595e-01  5.97147197e-02]
  [-3.78368143e-03 -8.08533356e-02 -9.21200588e-02]
  [-1.05731510e-01 -3.19677964e-02 -4.00087237e-02]]

 [[-1.34399235e-01 -1.31620303e-01  2.74317771e-01]
  [-6.33577555e-02  8.76044184e-02 -5.13922714e-05]
  [-4.42624427e-02 -9.32039022e-02 -5.32314554e-02]]

 [[ 1.36276722e-01 -8.72253329e-02  5.73716164e-02]


In [ ]:
# fc0 = FC(7 * 7 * 16, 7 * 7 * 16)
# weights_fc0 = fc0.get_weights
# print(weights_fc0)

In [ ]:
# Define FP16 copy of weights
conv0_fp16 = Conv3x3_1_to_n_padding(output=8, dtype=np.float16)
conv1_fp16 = Conv3x3_n_to_n_padding(output=16, inputch=8, dtype=np.float16)
fc0_fp16 = FC(7 * 7 * 16, 7 * 7 * 16, dtype=np.float16)
fc1_fp16 = FC(7 * 7 * 16, 10, dtype=np.float16)

In [ ]:
# conv0_fp16 = Conv3x3_1_to_n_padding(output=8, dtype=np.float16)
# weights = conv0_fp16.filters
# print(weights)

In [ ]:
# Define scaling factor
S = 128.0

In [ ]:
# Initialize the network weights
conv0.initialize_weights()
conv1.initialize_weights()
fc0.initialize_weights()
fc1.initialize_weights()

In [ ]:
# import sys

# def forward(im, label, debug=False):
#     im = (im / 255) - 0.5

#     # Conv 0 with Pool
#     out_conv0 = conv0.forward(im)
#     out_pool0 = pool0.forward(out_conv0)
#     sys.stdout.write(f"Conv 0 output shape: {out_pool0.shape}\n")
#     sys.stdout.flush()

#     # Conv 1 with Pool
#     out_conv1 = conv1.forward(out_pool0)
#     out_pool1 = pool1.forward(out_conv1)
#     sys.stdout.write(f"Conv 1 output shape: {out_pool1.shape}\n")
#     sys.stdout.flush()

#     # Flatten the output for FC0
#     out_pool1_flat = out_pool1.flatten()

#     # FC0 and Relu
#     out_fc0 = fc0.forward(out_pool1_flat)
#     sys.stdout.write(f"FC0 output shape: {out_fc0.shape}\n")
#     sys.stdout.flush()

#     # FC1 and SoftMax
#     out_fc1 = fc1.forward(out_fc0)
#     out_soft = softmax.forward(out_fc1)
#     sys.stdout.write(f"Softmax output shape: {out_soft.shape}\n")
#     sys.stdout.flush()

#     # Compute the loss
#     loss = cal_loss(out_soft, label)

#     # Compute the accuracy
#     acc = compute_accuracy(out_soft, label)

#     np.save('saved_weights.npy', model)


#     return loss, acc, out_soft, weights

In [ ]:
# import sys
# import numpy as np

# def forward(im, label, debug=False):
#     im = (im / 255) - 0.5
#     im = im.reshape((28, 28, 1))


#     # Conv 0 with Pool
#     out_conv0 = conv0.forward(im)
#     out_pool0 = pool0.forward(out_conv0)
#     sys.stdout.write(f"Conv 0 output shape: {out_pool0.shape}\n")
#     sys.stdout.flush()

#     # Conv 1 with Pool
#     out_conv1 = conv1.forward(out_pool0)
#     out_pool1 = pool1.forward(out_conv1)
#     sys.stdout.write(f"Conv 1 output shape: {out_pool1.shape}\n")
#     sys.stdout.flush()

#     # Flatten the output for FC0
#     out_pool1_flat = out_pool1.flatten()

#     # FC0 and Relu
#     out_fc0 = fc0.forward(out_pool1_flat)
#     sys.stdout.write(f"FC0 output shape: {out_fc0.shape}\n")
#     sys.stdout.flush()

#     # FC1 and SoftMax
#     out_fc1 = fc1.forward(out_fc0)
#     out_soft = softmax.forward(out_fc1)
#     sys.stdout.write(f"Softmax output shape: {out_soft.shape}\n")
#     sys.stdout.flush()

#    # After performing forward propagation
# conv0_weights = conv0.filters
# conv1_weights = conv1.filters
# fc0_weights = fc0.weights
# fc1_weights = fc1.weights

# # Save the weights to a file
# np.savez('weights.npz', conv0_weights=conv0_weights, conv1_weights=conv1_weights,
#          fc0_weights=fc0_weights, fc1_weights=fc1_weights)

In [ ]:
print("Testing...")

Testing...


In [ ]:
# create a random 2D numpy array as the input
input = np.random.rand(28, 28)

# create an instance of the Conv3x3 class
conv0 = Conv3x3(num_filters=8)
pool0 = MaxPool2()

# Forward pass
out_conv0 = conv0.forward(input)
out_pool0 = pool0.forward(out_conv0)

# Print the output after each layer
print("Conv1 output shape:", out_conv0.shape)
print("MaxPool1 output shape:", out_pool0.shape)


Conv1 output shape: (26, 26, 8)
MaxPool1 output shape: (13, 13, 8)


In [ ]:
# create a random 2D numpy array as the input
input = np.random.rand(14, 14)

# create an instance of the Conv3x3 class
conv1 = Conv3x3(num_filters=16)
pool1 = MaxPool2()

# Forward pass
out_conv1 = conv1.forward(input)
out_pool1 = pool1.forward(out_conv1)

# Print the output after each layer
print("Conv1 output shape:", out_conv1.shape)
print("MaxPool1 output shape:", out_pool1.shape)

Conv1 output shape: (12, 12, 16)
MaxPool1 output shape: (6, 6, 16)


In [ ]:
# # Backward propagation using FP32 weights
# def backward(label, out, loss=1, debug=False):
#     # Compute the gradient of the Softmax layer
#     gradient = out
#     gradient[label] -= 1

#     # Backpropagate through the softmax layer
#     grad_softmax = softmax.backward(gradient)

#     # Backpropagate through the fc1 layer
#     grad_fc1 = fc1.backward(grad_softmax)

#     # Backpropagate through the FC0 layer
#     grad_fc0 = fc0.backward(grad_fc1)

#     grad_pool1_flat = grad_pool1.flatten() 
       
#     # Backpropagate through the MaxPool1 layer
#     grad_pool1 = pool1.backward(grad_pool1_flat)

#     # Backpropagate through the Conv1 layer
#     grad_conv1 = conv1.backward(grad_pool1)

#     # Backpropagate through the MaxPool0 layer
#     grad_pool0 = pool0.backward(grad_conv1)

#     # Backpropagate through the Conv0 layer
#     grad_conv0 = conv0.backward(grad_pool0)

In [ ]:
# Forward propagation using FP16 weights
def forward_fp16(im, label, debug=False):
    im = (im / 255) - 0.5
    im = im.reshape((28, 28, 1))
    
    print("Input shape:", im.shape)
    # print("Weights shape:", self.weights.shape)

    # Conv 0 with Pool
    out_conv0 = conv0_fp16.forward(im)
    out_pool0 = pool0.forward(out_conv0)

    # Conv 1 with Pool
    out_conv1 = conv1_fp16.forward(out_pool0)
    out_pool1 = pool1.forward(out_conv1)

    out_pool1_flat = out_pool1.flatten()
    
    # FC0 and Relu
    out_fc0 = fc0_fp16.forward(out_pool1_flat)

    # FC1 and SoftMax
    out_fc1 = fc1_fp16.forward(out_fc0)
    out_soft = softmax.forward(out_fc1)


    # Reshape out_fc1
    out_fc1_reshaped = out_fc1.reshape((1, -1))

     # Calculate loss
    loss_ = cal_loss(out_soft, label)

    # Calculate accuracy
    acc_ = cal_accuracy(out_soft, label)

    return loss_, acc_, out_soft

    
# After performing forward propagation
conv0_weights = conv0_fp16.filters
conv1_weights = conv1_fp16.filters
fc0_weights = fc0_fp16.weights
fc1_weights = fc1_fp16.weights
pool0_weights = pool0.weights
pool1_weights = pool1.weights
# out_poolflat_weights = out_pool1_flat.weight


print("conv0" , conv0_fp16.filters)
print("conv1" , conv1_fp16.filters)
print("fc0" , fc0_fp16.weights)
print("fc10" , fc1_fp16.weights)
print("pool0" , pool0.weights)
print("pool1" , pool1.weights)
# print("flat_pool1" , out_pool1.weights)

print("conv0" , conv0_fp16.filters.shape)
print("conv1" , conv1_fp16.filters.shape)
print("fc0" , fc0_fp16.weights.shape)
print("fc10" , fc1_fp16.weights.shape)
# print("pool0" , pool0.weights.shape)
# print("pool1" , pool1.weights.shape)
# # print("flat_pool1" , out_pool1.weights.shape)

# Save the weights to a file
np.savez('weights_fp16.npz', conv0_weights=conv0_weights, conv1_weights=conv1_weights,
         fc0_weights=fc0_weights, fc1_weights=fc1_weights)

conv0 [[[ 0.1613   -0.02892   0.06433 ]
  [-0.0711   -0.1395   -0.112   ]
  [ 0.01545   0.1348    0.0941  ]]

 [[-0.1616   -0.0686   -0.0792  ]
  [ 0.01692   0.074     0.0287  ]
  [ 0.08704  -0.1393    0.0636  ]]

 [[ 0.06     -0.04977   0.097   ]
  [ 0.03622  -0.2458    0.06903 ]
  [ 0.01442   0.04132  -0.07385 ]]

 [[ 0.0519   -0.2006    0.1353  ]
  [ 0.03424   0.1929    0.1405  ]
  [-0.228     0.131     0.04965 ]]

 [[ 0.04517   0.01967   0.10614 ]
  [-0.1854   -0.05838  -0.0786  ]
  [-0.02339  -0.11926   0.0336  ]]

 [[-0.04675  -0.01074   0.0894  ]
  [ 0.0716   -0.013535 -0.0889  ]
  [-0.074    -0.07     -0.1558  ]]

 [[ 0.05725   0.03387  -0.0365  ]
  [-0.1461   -0.014565  0.10657 ]
  [ 0.1237   -0.1487   -0.02368 ]]

 [[-0.1853    0.07666  -0.11285 ]
  [ 0.0959   -0.05344  -0.00989 ]
  [-0.3098    0.0676    0.0879  ]]]
conv1 [[[[-5.9143e-02  2.7661e-01  7.6111e-02 ...  4.3335e-02 -8.6914e-02
    -1.8738e-01]
   [-1.3696e-01 -4.0924e-02  1.9983e-01 ...  1.7004e-01 -9.0027e-03
   

In [ ]:
# # Backward propagation using FP16 weights
# # Backward propagation using FP16 weights
# def backward(label, out, loss=1, debug=False):
#     # Compute the gradient of the Softmax layer
#     gradient = out
#     gradient[label] -= 1

#     # Backpropagate through the softmax layer
#     grad_softmax = softmax.backward(gradient)

#     # Backpropagate through the fc1 layer
#     grad_fc1 = fc1_fp16.backward(grad_softmax , lr)

#     # Backpropagate through the FC0 layer
#     grad_fc0 = fc0_fp16.backward(grad_fc1 , lr)

#     # Reshape gradient_fc0 to match the dimensions before swapping axes
#     gradient_fc0_reshape = grad_fc0.reshape((1, 64, 7, 7))

#     # Swap axes to realign for flattening
#     gradient_swap0 = np.swapaxes(gradient_fc0_reshape, 1, 2)
#     gradient_swap1 = np.swapaxes(gradient_swap0, 2, 3)

#     # # Backpropagate through the FC0 layer
#     # grad_fc0 = fc0_fp16.backward(grad_fc1 , lr)
    

#     # # grad_pool1_flat = grad_pool1.flatten() 
#     # # Swap axes to realign for flattening
#     # gradient_swap0 = grad_fc0
#     # gradient_swap1 = np.swapaxes(gradient_swap0, 0, 2)
       
#     # Backpropagate through the MaxPool1 layer
#     grad_pool1 = pool1.backward(gradient_swap1)

#     # Backpropagate through the Conv1 layer
#     grad_conv1 = conv1_fp16.backward(grad_pool1 , lr)

#     # Backpropagate through the MaxPool0 layer
#     grad_pool0 = pool0.backward(grad_conv1)

#     # Backpropagate through the Conv0 layer
#     grad_conv0 = conv0_fp16.backward(grad_pool0 , lr)


# Backward propagation using FP16 weights
def backward_fp16(label, out, loss=1, debug=False):
    # Compute the gradient of the Softmax layer
    gradient = out
    gradient[label] -= 1

    # Backpropagate through the Softmax layer
    grad_softmax = softmax.backward(gradient)

    # Backpropagate through the FC1 layer
    grad_fc1 = fc1_fp16.backward(grad_softmax , lr)

    # Backpropagate through the FC0 layer
    grad_fc0 = fc0_fp16.backward(grad_fc1 , lr)

    # Reshape the gradient to match the shape of the output of the pool1 layer
    grad_fc0_reshaped = grad_fc0.reshape(1, 16, 7, 7)

    # Backpropagate through the MaxPool1 layer
    grad_pool1 = pool1.backward(grad_fc0_reshaped)

    # Backpropagate through the Conv1 layer
    grad_conv1 = conv1_fp16.backward(grad_pool1 , lr)

    # Backpropagate through the MaxPool0 layer
    grad_pool0 = pool0.backward(grad_conv1)

    # Backpropagate through the Conv0 layer
    grad_conv0 = conv0_fp16.backward(grad_pool0 , lr)

    # Update the weights and biases of the layers
    conv0_fp16.update_weights(lr)
    conv1_fp16.update_weights(lr)
    fc0_fp16.update_weights(lr)
    fc1_fp16.update_weights(lr)

    # Calculate the loss and accuracy
    loss_ = cal_loss(out, label)
    acc_ = cal_accuracy(out, label)

    return loss_, acc_

In [ ]:
# # Defining the network - Loss Function (Cross Entropy)
# # Calculate cross-entropy loss and accuracy. np.log() is the natural log.
# def cal_loss(out_soft, label):
#   loss = -np.log(out_soft[label])
#   acc = 1 if np.argmax(out_soft) == label else 0
#   return out_soft, loss, acc

def cal_accuracy(out_soft, label):
    if out_soft.ndim > 1:
        predicted_labels = np.argmax(out_soft, axis=1)
    else:
        predicted_labels = out_soft.round().astype(int)
    accuracy = np.mean(predicted_labels == label)
    return accuracy

In [ ]:
# Defining the network - Loss Function (Cross Entropy)
# Calculate cross-entropy loss and accuracy. np.log() is the natural log.
def cal_loss(out_soft, label):
  loss = -np.log(out_soft[label])
  acc = 1 if np.argmax(out_soft) == label else 0
  return out_soft, loss, acc

In [ ]:
# Defining the network - Training Function
def train(im, label, debug=False, lr=.005):
  pred = forward_fp16(im, label, debug)
  out_soft, loss, acc = cal_loss(pred, label)
  backward(label, out_soft, loss=loss, lr=0.005)
  return loss, acc

In [ ]:
# Defining the network - Validation Function
def val(im, label):
  pred = forward_fp16(im, label)
  out_soft, loss, acc = cal_loss(pred, label)
  return loss, acc

In [ ]:
# Function definitions to save and load weight files

def save_weights(name,lr=0,max_acc=0):
  print(f"\nSaving new weights ({name}).")
  weights = dict()
  weights["conv0"]        = conv0.filters
  weights["conv1"]        = conv1.filters
  weights["fc0_weights"]  = fc0.weights
  weights["fc0_biases" ]  = fc0.biases
  weights["fc1_weights"]  = fc1.weights
  weights["fc1_biases" ]  = fc1.biases
  weights["lr" ]          = lr
  weights["max_acc"]      = max_acc
  weight_file = open(str(name), "wb")
  pickle.dump(weights, weight_file)
  weight_file.close()
  
def load_weights(name):
  if os.path.isfile(name): 
    weight_file = open(str(name), "rb")
    weights = pickle.load(weight_file)
    conv0.filters  = weights["conv0"]      
    conv1.filters  = weights["conv1"]      
    fc0.weights    = weights["fc0_weights"]
    fc0.biases     = weights["fc0_biases" ]
    fc1.weights    = weights["fc1_weights"]
    fc1.biases     = weights["fc1_biases" ]
    lr             = weights["lr" ]
    max_acc        = weights["max_acc"]
    print(f"\nLoading weights from {name} file. LR restored to {lr}. Last Accuracy {max_acc}%")
    return lr, max_acc
  else:
    print("Weights file not found.")
    lr=0.005
    max_acc=0
    return lr, max_acc
   

In [ ]:
# Defining the network - Adjust learning rate
def adjust_lr(acc, lr=.005):
  if   acc > 98: lr=0.00001
  elif acc > 95: lr=0.0005
  elif acc > 90: lr=0.001
  elif acc > 80: lr=0.002
  elif acc > 70: lr=0.003
  elif acc > 60: lr=0.004
  return lr

In [ ]:
# Load Weights
if load_saved_weights:
    lr, max_acc = load_weights(weight_file)
else:
    lr, max_acc = 0.005, 0 

if debug: save_weights(f'weights/debug.pkl', lr, max_acc)

In [ ]:
# Importing the training dataset - MNIST Dataset

train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

In [ ]:
# Shuffle Data
permutation = np.random.permutation(len(train_images))
train_images = train_images[permutation]
train_labels = train_labels[permutation]

In [ ]:
 # Main function to run the training
 # please runnnnho jaa yarr 
 # plzzz help ALLAH plzzzzz plzzzz
 # tere banda mushkilon ma hai girha 
 # please ALLAH g mere ye project bohat acha ho jae AMEEN SUM AMEEN 

if run_train:
  print(f'Training Initialized.')
  print(f"\tTotal number of training   images: {len(train_labels)}")
  print(f"\tTotal number of validation images: {len(test_labels)}")
  print(f"\tTraining will run for {total_epoch} epochs.")
  print(f"\tResults will be logged after every {training_acc_internal} images.")
  # Training loop
for epoch in range(3):
    loss = 0
    num_correct = 0
    for i, (im, label) in enumerate(zip(mnist.train_images(), mnist.train_labels())):
        # Forward propagation using FP32 weights
        loss_, acc_, out_ = forward_fp16(im, label)

        # Backward propagation using FP32 weights
        backward(label, out_, loss_)

        # Forward propagation using FP16 weights
        loss_, acc_, out_ = forward_fp16(im, label)

        # Scale the gradients
        conv0_fp16.weights_grad /= S
        conv1_fp16.weights_grad /= S
        fc0_fp16.weights_grad /= S
        fc1_fp16.weights_grad /= S

        # Update the weights
        conv0.weights -= conv0_fp16.weights_grad
        conv1.weights -= conv1_fp16.weights_grad
        fc0.weights -= fc0_fp16.weights_grad
        fc1.weights -= fc1_fp16.weights_grad

        loss += loss_
        num_correct += acc_

    print(f"Epoch: {epoch}, Loss: {loss / len(mnist.train_images())}, Accuracy: {num_correct / len(mnist.train_images()) * 100}%")

Training Initialized.
	Total number of training   images: 60000
	Total number of validation images: 10000
	Training will run for 1 epochs.
	Results will be logged after every 1000 images.
Input shape: (28, 28, 1)


ValueError: ignored

In [ ]:
# Training loop
for epoch in range(3):
    loss = 0
    num_correct = 0
    for i, (im, label) in enumerate(zip(mnist.train_images(), mnist.train_labels())):
        # Forward propagation using FP32 weights
        loss_, acc_, out_ = forward(im, label)

        # Backward propagation using FP32 weights
        backward(label, out_, loss_)

        # Forward propagation using FP16 weights
        loss_, acc_, out_ = forward_fp16(im, label)

        # Scale the gradients
        conv0_fp16.weights_grad /= S
        conv1_fp16.weights_grad /= S
        fc0_fp16.weights_grad /= S
        fc1_fp16.weights_grad /= S

        # Update the weights
        conv0.weights -= conv0_fp16.weights_grad
        conv1.weights -= conv1_fp16.weights_grad
        fc0.weights -= fc0_fp16.weights_grad
        fc1.weights -= fc1_fp16.weights_grad

        loss += loss_
        num_correct += acc_

    print(f"Epoch: {epoch}, Loss: {loss / len(mnist.train_images())}, Accuracy: {num_correct / len(mnist.train_images()) * 100}%")